repos:
-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        description: Formats C/C++ files.
        entry: clang-format-18
        language: system
        files: \.(c|h|cpp|hpp|cc|hh|cxx|hxx)$
        args: ['-i', '-style=file']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
